name: Booking API Tests

on:
  workflow_dispatch:


jobs:
  Booking_API_Tests:
    runs-on: ubuntu-latest

    env:
      API_USERNAME: ${{ secrets.BOOKING_API_USERNAME }}
      API_PASSWORD: ${{ secrets.BOOKING_API_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          pytest tests/test_booking_api.py

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/report.html
